version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 3001:3000
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    env_file: .env
    links:
      - db
    environment:
      PMA_HOST: $PMA_HOST
      PMA_PORT: $PMA_PORT
      PMA_ARBITRARY: $PMA_ARBITRARY
    restart: always
    ports:
      - 8081:80
volumes: 
  db: